/**
 * 智能会话标题生成器 (T047)
 *
 * 基于对话内容自动生成会话标题和摘要。
 *
 * @module sdk/session/title-generator
 */

import { getLogger } from '@logtape/logtape';
import type {
  SessionTitleOptions,
  SessionTitleResult,
  SessionSummaryOptions,
  SessionSummaryResult,
  LLMMessage,
} from '../runtime';

const log = getLogger(['sdk', 'session', 'title-generator']);

/** 标题生成器配置 */
export interface TitleGeneratorConfig {
  /** 最大标题长度 */
  maxTitleLength: number;
  /** 最大摘要长度 */
  maxSummaryLength: number;
  /** 生成标题的最小消息数 */
  minMessagesForTitle: number;
  /** 语言 */
  language: 'zh' | 'en' | 'auto';
}

/** 标题生成结果 */
export interface TitleGenerationResult {
  /** 标题 */
  title: string;
  /** 摘要 */
  summary: string | null;
  /** 置信度 */
  confidence: number;
  /** 关键主题 */
  keyTopics: string[];
}

/** 默认配置 */
const DEFAULT_CONFIG: TitleGeneratorConfig = {
  maxTitleLength: 50,
  maxSummaryLength: 200,
  minMessagesForTitle: 2,
  language: 'auto',
};

/** 关键词提取正则模式 */
const TOPIC_PATTERNS = [
  // 问题模式
  /(?:如何|怎么|怎样|如何能够|怎样才能)([^？?]+)/g,
  /(?:什么是|什么是)([^？?]+)/g,
  /(?:为什么|为何)([^？?]+)/g,
  // 请求模式
  /(?:帮我|请|请帮我|帮我写|帮我做|帮我生成)([^。！？.!?]+)/g,
  // 英文模式
  /(?:how to|what is|why|help me|please)([^.!?]+)/gi,
];

/** 停用词列表 */
const STOP_WORDS = new Set([
  // 中文停用词
  '的', '了', '是', '在', '我', '有', '和', '就', '不', '人', '都', '一', '一个',
  '上', '也', '很', '到', '说', '要', '去', '你', '会', '着', '没有', '看', '好',
  '自己', '这', '那', '个', '里', '吗', '呢', '啊', '吧', '嗯', '哦',
  // 英文停用词
  'the', 'a', 'an', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
  'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could', 'should',
  'i', 'you', 'he', 'she', 'it', 'we', 'they', 'me', 'him', 'her', 'us', 'them',
  'this', 'that', 'these', 'those', 'what', 'which', 'who', 'when', 'where', 'why',
  'how', 'all', 'each', 'every', 'both', 'few', 'more', 'most', 'other', 'some',
  'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very',
]);

/**
 * 智能会话标题生成器
 *
 * 职责：
 * - 基于对话内容生成标题
 * - 提取关键主题
 * - 生成会话摘要
 *
 * @example
 * ```ts
 * const generator = new TitleGenerator();
 * const result = await generator.generateTitle(messages);
 * console.log(result.title);
 * ```
 */
export class TitleGenerator {
  private config: TitleGeneratorConfig;
  private llmProvider?: {
    generate: (prompt: string) => Promise<string>;
  };

  constructor(config?: Partial<TitleGeneratorConfig>) {
    this.config = { ...DEFAULT_CONFIG, ...config };
  }

  /**
   * 设置 LLM 提供者（可选，用于更智能的标题生成）
   */
  setLLMProvider(provider: { generate: (prompt: string) => Promise<string> }): void {
    this.llmProvider = provider;
  }

  /**
   * 生成会话标题
   *
   * @param messages - 对话消息列表
   * @param options - 生成选项
   * @returns 标题生成结果
   */
  async generateTitle(
    messages: LLMMessage[],
    options?: SessionTitleOptions
  ): Promise<SessionTitleResult> {
    if (messages.length < this.config.minMessagesForTitle) {
      return {
        title: '新对话',
        confidence: 0,
        isAutoGenerated: false,
      };
    }

    // 优先使用 LLM 生成
    if (this.llmProvider) {
      try {
        const title = await this.generateTitleWithLLM(messages, options);
        return {
          title,
          confidence: 0.9,
          isAutoGenerated: true,
        };
      } catch (error) {
        log.warn('LLM 标题生成失败，回退到规则生成', { error: String(error) });
      }
    }

    // 回退到规则生成
    return this.generateTitleWithRules(messages, options);
  }

  /**
   * 生成会话摘要
   *
   * @param messages - 对话消息列表
   * @param options - 生成选项
   * @returns 摘要生成结果
   */
  async generateSummary(
    messages: LLMMessage[],
    options?: SessionSummaryOptions
  ): Promise<SessionSummaryResult> {
    if (messages.length === 0) {
      return {
        summary: '',
        keyTopics: [],
        entities: [],
        tokensUsed: 0,
      };
    }

    // 提取关键主题
    const keyTopics = this.extractKeyTopics(messages);

    // 提取实体
    const entities = this.extractEntities(messages);

    // 优先使用 LLM 生成摘要
    if (this.llmProvider) {
      try {
        const summary = await this.generateSummaryWithLLM(messages, keyTopics, options);
        return {
          summary,
          keyTopics,
          entities,
          tokensUsed: this.estimateTokens(summary),
        };
      } catch (error) {
        log.warn('LLM 摘要生成失败，回退到规则生成', { error: String(error) });
      }
    }

    // 回退到规则生成
    const summary = this.generateSummaryWithRules(messages, keyTopics, options);
    return {
      summary,
      keyTopics,
      entities,
      tokensUsed: this.estimateTokens(summary),
    };
  }

  /**
   * 批量生成标题和摘要
   *
   * @param messages - 对话消息列表
   * @returns 生成结果
   */
  async generateTitleAndSummary(
    messages: LLMMessage[]
  ): Promise<TitleGenerationResult> {
    const [titleResult, summaryResult] = await Promise.all([
      this.generateTitle(messages),
      this.generateSummary(messages),
    ]);

    return {
      title: titleResult.title,
      summary: summaryResult.summary,
      confidence: titleResult.confidence,
      keyTopics: summaryResult.keyTopics,
    };
  }

  // ========== 私有方法 ==========

  /**
   * 使用 LLM 生成标题
   */
  private async generateTitleWithLLM(
    messages: LLMMessage[],
    options?: SessionTitleOptions
  ): Promise<string> {
    const userMessages = messages.filter(m => m.role === 'user');
    const firstUserMessage = userMessages[0];
    const content = typeof firstUserMessage.content === 'string'
      ? firstUserMessage.content
      : JSON.stringify(firstUserMessage.content);

    const prompt = this.buildTitlePrompt(content, options);
    const title = await this.llmProvider!.generate(prompt);

    // 清理和截断
    return this.cleanTitle(title, options?.maxLength);
  }

  /**
   * 使用规则生成标题
   */
  private generateTitleWithRules(
    messages: LLMMessage[],
    options?: SessionTitleOptions
  ): SessionTitleResult {
    // 获取第一条用户消息
    const userMessages = messages.filter(m => m.role === 'user');
    const firstUserMessage = userMessages[0];

    if (!firstUserMessage) {
      return {
        title: '新对话',
        confidence: 0,
        isAutoGenerated: false,
      };
    }

    const content = typeof firstUserMessage.content === 'string'
      ? firstUserMessage.content
      : JSON.stringify(firstUserMessage.content);

    // 提取主题
    const topics = this.extractKeyTopics([firstUserMessage]);

    if (topics.length > 0) {
      // 使用第一个主题作为标题
      const title = this.cleanTitle(topics[0], options?.maxLength);
      return {
        title,
        confidence: 0.7,
        isAutoGenerated: true,
      };
    }

    // 截取前 50 个字符作为标题
    const title = this.cleanTitle(content, options?.maxLength);
    return {
      title,
      confidence: 0.5,
      isAutoGenerated: true,
    };
  }

  /**
   * 使用 LLM 生成摘要
   */
  private async generateSummaryWithLLM(
    messages: LLMMessage[],
    keyTopics: string[],
    options?: SessionSummaryOptions
  ): Promise<string> {
    const content = messages
      .slice(0, 10) // 只使用前 10 条消息
      .map(m => {
        const c = typeof m.content === 'string' ? m.content : JSON.stringify(m.content);
        return `${m.role}: ${c}`;
      })
      .join('\n');

    const prompt = this.buildSummaryPrompt(content, keyTopics, options);
    const summary = await this.llmProvider!.generate(prompt);

    return this.cleanSummary(summary, options?.maxLength);
  }

  /**
   * 使用规则生成摘要
   */
  private generateSummaryWithRules(
    messages: LLMMessage[],
    keyTopics: string[],
    options?: SessionSummaryOptions
  ): string {
    const maxLength = options?.maxLength ?? this.config.maxSummaryLength;

    // 构建摘要：主题 + 关键消息摘要
    const parts: string[] = [];

    if (keyTopics.length > 0) {
      parts.push(`主题: ${keyTopics.slice(0, 3).join(', ')}`);
    }

    // 获取首尾用户消息
    const userMessages = messages.filter(m => m.role === 'user');
    if (userMessages.length > 0) {
      const firstMsg = typeof userMessages[0].content === 'string'
        ? userMessages[0].content
        : JSON.stringify(userMessages[0].content);

      parts.push(`问题: ${firstMsg.slice(0, 80)}${firstMsg.length > 80 ? '...' : ''}`);
    }

    if (userMessages.length > 1) {
      const lastMsg = typeof userMessages[userMessages.length - 1].content === 'string'
        ? userMessages[userMessages.length - 1].content
        : JSON.stringify(userMessages[userMessages.length - 1].content);

      parts.push(`后续: ${lastMsg.slice(0, 50)}${lastMsg.length > 50 ? '...' : ''}`);
    }

    const summary = parts.join(' | ');
    return summary.slice(0, maxLength);
  }

  /**
   * 提取关键主题
   */
  private extractKeyTopics(messages: LLMMessage[]): string[] {
    const text = messages
      .filter(m => m.role === 'user')
      .map(m => typeof m.content === 'string' ? m.content : JSON.stringify(m.content))
      .join(' ');

    const topics: string[] = [];

    // 使用正则模式提取
    for (const pattern of TOPIC_PATTERNS) {
      let match;
      while ((match = pattern.exec(text)) !== null) {
        const topic = match[1]?.trim();
        if (topic && topic.length > 2 && topic.length < 30) {
          topics.push(topic);
        }
      }
    }

    // 提取关键词
    const keywords = this.extractKeywords(text);
    topics.push(...keywords);

    // 去重并返回
    return [...new Set(topics)].slice(0, 5);
  }

  /**
   * 提取关键词
   */
  private extractKeywords(text: string): string[] {
    // 分词（简单实现：按空格和标点分割）
    const words = text
      .toLowerCase()
      .split(/[\s,，。！？!?.;；：:""'']+/)
      .filter(w => w.length > 1 && !STOP_WORDS.has(w));

    // 统计词频
    const wordCount: Record<string, number> = {};
    for (const word of words) {
      wordCount[word] = (wordCount[word] ?? 0) + 1;
    }

    // 按频率排序
    return Object.entries(wordCount)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 10)
      .map(([word]) => word);
  }

  /**
   * 提取实体（人名、地名、机构名等）
   */
  private extractEntities(messages: LLMMessage[]): string[] {
    const text = messages
      .map(m => typeof m.content === 'string' ? m.content : JSON.stringify(m.content))
      .join(' ');

    const entities: string[] = [];

    // 简单的实体识别模式
    const patterns = [
      // 专有名词（大写开头的英文）
      /\b[A-Z][a-z]+(?:\s+[A-Z][a-z]+)*\b/g,
      // 中文专有名词标记
      /(?:公司|组织|项目|产品|系统|框架|语言)[：:]?\s*([^\s,，。！？!?.]+)/g,
      // 引号中的实体
      /["「『"]([^"」』"]+)["」』"]/g,
    ];

    for (const pattern of patterns) {
      let match;
      while ((match = pattern.exec(text)) !== null) {
        const entity = match[1]?.trim() ?? match[0]?.trim();
        if (entity && entity.length > 1 && entity.length < 20) {
          entities.push(entity);
        }
      }
    }

    return [...new Set(entities)].slice(0, 10);
  }

  /**
   * 构建标题生成提示词
   */
  private buildTitlePrompt(content: string, options?: SessionTitleOptions): string {
    const language = options?.language ?? this.config.language;
    const languageHint = language === 'zh'
      ? '用中文'
      : language === 'en'
        ? 'in English'
        : 'in the same language as the content';

    return `请为以下对话生成一个简短的标题（不超过 ${options?.maxLength ?? this.config.maxTitleLength} 字）。

规则：
1. 标题应该简洁明了，概括对话主题
2. ${languageHint}
3. 不要包含引号或其他标点
4. 只返回标题，不要其他内容

对话内容：
${content.slice(0, 500)}

标题：`;
  }

  /**
   * 构建摘要生成提示词
   */
  private buildSummaryPrompt(
    content: string,
    keyTopics: string[],
    options?: SessionSummaryOptions
  ): string {
    const language = options?.language ?? this.config.language;
    const languageHint = language === 'zh'
      ? '用中文'
      : language === 'en'
        ? 'in English'
        : 'in the same language as the content';

    return `请为以下对话生成一个摘要（不超过 ${options?.maxLength ?? this.config.maxSummaryLength} 字）。

规则：
1. 摘要应包含主要讨论内容和结论
2. ${languageHint}
3. 保持客观简洁
4. 只返回摘要，不要其他内容

关键主题：${keyTopics.join(', ')}

对话内容：
${content.slice(0, 1000)}

摘要：`;
  }

  /**
   * 清理标题
   */
  private cleanTitle(title: string, maxLength?: number): string {
    const limit = maxLength ?? this.config.maxTitleLength;

    // 移除多余空白
    let cleaned = title.trim().replace(/\s+/g, ' ');

    // 移除可能的引号
    cleaned = cleaned.replace(/^["「『"]+|["」』"]+$/g, '');

    // 移除 "标题：" 前缀
    cleaned = cleaned.replace(/^(标题|Title)[：:]\s*/i, '');

    // 截断
    if (cleaned.length > limit) {
      cleaned = cleaned.slice(0, limit - 3) + '...';
    }

    return cleaned || '新对话';
  }

  /**
   * 清理摘要
   */
  private cleanSummary(summary: string, maxLength?: number): string {
    const limit = maxLength ?? this.config.maxSummaryLength;

    // 移除多余空白和换行
    let cleaned = summary.trim().replace(/\s+/g, ' ');

    // 移除 "摘要：" 前缀
    cleaned = cleaned.replace(/^(摘要|Summary)[：:]\s*/i, '');

    // 截断
    if (cleaned.length > limit) {
      // 尝试在句子边界截断
      const lastPeriod = cleaned.slice(0, limit).lastIndexOf('。');
      const lastDot = cleaned.slice(0, limit).lastIndexOf('.');
      const cutPoint = Math.max(lastPeriod, lastDot);

      if (cutPoint > limit * 0.7) {
        cleaned = cleaned.slice(0, cutPoint + 1);
      } else {
        cleaned = cleaned.slice(0, limit - 3) + '...';
      }
    }

    return cleaned;
  }

  /**
   * 估算 Token 数量
   */
  private estimateTokens(text: string): number {
    return Math.ceil(text.length / 3);
  }
}

// ========== 便捷函数 ==========

/**
 * 快速生成标题
 */
export async function generateSessionTitle(
  messages: LLMMessage[],
  options?: SessionTitleOptions
): Promise<SessionTitleResult> {
  const generator = new TitleGenerator();
  return generator.generateTitle(messages, options);
}

/**
 * 快速生成摘要
 */
export async function generateSessionSummary(
  messages: LLMMessage[],
  options?: SessionSummaryOptions
): Promise<SessionSummaryResult> {
  const generator = new TitleGenerator();
  return generator.generateSummary(messages, options);
}
