/**
 * 会话类型定义
 *
 * 注意：此文件为零依赖的纯类型定义。
 * 如需运行时校验，请在 runtime 层或 SDK 层定义 Zod Schema。
 */

import type { ChannelType } from './interfaces';
import type { LLMMessage } from './message';

/** 会话 ID */
export type SessionId = string;

/** 会话键（格式：channel:chatId） */
export type SessionKey = `${string}:${string}`;

/** 会话状态 */
export type SessionState = 'active' | 'idle' | 'closed' | 'archived';

/** 会话标签 */
export type SessionTag = string;

// ============================================================
// T043: 会话上下文配置类型
// ============================================================

/** 上下文注入策略 */
export type ContextInjectionStrategy = 'sliding_window' | 'summary' | 'hybrid';

/** 会话上下文配置 */
export interface SessionContextConfig {
  /** 是否启用上下文注入 */
  enabled: boolean;
  /** 注入策略 */
  strategy: ContextInjectionStrategy;
  /** 历史消息最大数量 */
  maxHistoryMessages: number;
  /** 历史消息 Token 预算 */
  historyTokenBudget: number;
  /** 相关会话摘要数量 */
  maxRelatedSummaries: number;
  /** 相关会话摘要 Token 预算 */
  summaryTokenBudget: number;
  /** 是否包含系统消息 */
  includeSystemMessages: boolean;
  /** 是否自动生成标题 */
  autoGenerateTitle: boolean;
  /** 是否自动生成摘要 */
  autoGenerateSummary: boolean;
}

/** 相关会话摘要 */
export interface RelatedSessionSummary {
  /** 会话键 */
  sessionKey: string;
  /** 标题 */
  title: string;
  /** 摘要内容 */
  summary: string;
  /** 相关性分数 */
  relevanceScore: number;
}

/** 会话上下文注入结果 */
export interface SessionContextInjection {
  /** 注入的历史消息 */
  historyMessages: unknown[];
  /** 历史消息使用的 Token */
  historyTokensUsed: number;
  /** 注入的相关会话摘要 */
  relatedSummaries: RelatedSessionSummary[];
  /** 摘要使用的 Token */
  summaryTokensUsed: number;
  /** 总 Token 使用量 */
  totalTokensUsed: number;
  /** 是否截断 */
  wasTruncated: boolean;
}

// ============================================================
// 会话元数据和快照类型
// ============================================================

/** 会话元数据 */
export interface SessionMetadata {
  /** 通道类型 */
  channel: ChannelType;
  /** 聊天 ID */
  chatId: string;
  /** 工作目录 */
  workspace: string;
  /** 创建时间 */
  createdAt: Date;
  /** 最后活跃时间 */
  lastActiveAt: Date;
  /** 自定义元数据 */
  custom?: Record<string, unknown>;
}

/** 会话快照 */
export interface SessionSnapshot {
  /** 会话键 */
  sessionKey: SessionKey;
  /** 会话状态 */
  state: SessionState;
  /** 消息历史 */
  messages: LLMMessage[];
  /** 元数据 */
  metadata: SessionMetadata;
  /** Token 预算使用情况 */
  tokenUsage?: {
    used: number;
    budget: number;
  };
}

/** 会话存储接口 */
export interface SessionStore {
  /** 获取会话 */
  get(sessionKey: SessionKey): Promise<SessionSnapshot | undefined>;
  /** 保存会话 */
  save(session: SessionSnapshot): Promise<void>;
  /** 删除会话 */
  delete(sessionKey: SessionKey): Promise<void>;
  /** 列出所有活跃会话 */
  listActive(): Promise<SessionSnapshot[]>;
}

// ============================================================
// T046: 会话列表管理类型
// ============================================================

/** 会话列表项 */
export interface SessionListItem {
  /** 会话键 */
  sessionKey: SessionKey;
  /** 标题 */
  title: string | null;
  /** 摘要 */
  summary: string | null;
  /** 状态 */
  state: SessionState;
  /** 是否星标 */
  isStarred: boolean;
  /** 标签列表 */
  tags: SessionTag[];
  /** 消息数量 */
  messageCount: number;
  /** 创建时间 */
  createdAt: Date;
  /** 更新时间 */
  updatedAt: Date;
  /** 最后活跃时间 */
  lastActiveAt: Date;
}

/** 会话列表过滤选项 */
export interface SessionListFilter {
  /** 状态过滤 */
  state?: SessionState | SessionState[];
  /** 星标过滤 */
  isStarred?: boolean;
  /** 标签过滤 */
  tags?: SessionTag[];
  /** 搜索关键词 */
  search?: string;
  /** 时间范围 - 开始 */
  createdAfter?: Date;
  /** 时间范围 - 结束 */
  createdBefore?: Date;
}

/** 会话列表排序选项 */
export interface SessionListSort {
  /** 排序字段 */
  field: 'createdAt' | 'updatedAt' | 'lastActiveAt' | 'messageCount' | 'title';
  /** 排序方向 */
  order: 'asc' | 'desc';
}

/** 会话列表分页选项 */
export interface SessionListPagination {
  /** 页码（从 1 开始） */
  page: number;
  /** 每页数量 */
  pageSize: number;
}

/** 会话列表结果 */
export interface SessionListResult {
  /** 会话列表 */
  items: SessionListItem[];
  /** 总数量 */
  total: number;
  /** 当前页码 */
  page: number;
  /** 每页数量 */
  pageSize: number;
  /** 总页数 */
  totalPages: number;
}

// ============================================================
// T047: 会话标题生成类型
// ============================================================

/** 会话标题生成选项 */
export interface SessionTitleOptions {
  /** 最大标题长度 */
  maxLength?: number;
  /** 语言 */
  language?: 'zh' | 'en' | 'auto';
  /** 是否包含时间戳 */
  includeTimestamp?: boolean;
}

/** 会话摘要生成选项 */
export interface SessionSummaryOptions {
  /** 最大摘要长度 */
  maxLength?: number;
  /** 语言 */
  language?: 'zh' | 'en' | 'auto';
  /** 是否包含关键实体 */
  includeKeyEntities?: boolean;
}

/** 会话标题生成结果 */
export interface SessionTitleResult {
  /** 生成的标题 */
  title: string;
  /** 置信度 */
  confidence: number;
  /** 是否自动生成 */
  isAutoGenerated: boolean;
}

/** 会话摘要生成结果 */
export interface SessionSummaryResult {
  /** 生成的摘要 */
  summary: string;
  /** 关键主题 */
  keyTopics: string[];
  /** 提及的实体 */
  entities: string[];
  /** Token 使用量 */
  tokensUsed: number;
}